version: '3'
services:

  web:
    container_name: ${SITE_NAME}
    hostname: ${SITE_NAME}
    build:
      context: .
      dockerfile: party.dockerfile
    ports:
      - 8080:4545
    networks:
      - party
    environment:
      - PASSWORD=${PASSWORD}

networks:
  party:

